import type {
  ArchitectureReviewPacket,
  ArchitectureReviewRequest,
  ArchitectureReviewTemplate,
} from "@/lib/ecosystem-types";

type ReviewPacketInput = Omit<
  ArchitectureReviewRequest,
  "reviewPacket" | "id" | "createdAt" | "updatedAt"
>;

export function buildArchitectureReviewPacket(input: {
  request: ReviewPacketInput;
  template?: ArchitectureReviewTemplate;
  roadmapTarget?: string;
  ownerDirective?: string;
}): ArchitectureReviewPacket {
  const r = input.request;
  const template = input.template;
  const questions = [
    "Is the proposed direction architecturally sound for AION modular ecosystem?",
    "What are the top 3 runtime risks on Android OEM devices?",
    "What scaling/storage limits should we enforce in V1?",
    "Should execution continue in parallel or pause this subsystem?",
    "What validation evidence is required before production-ready?",
  ];

  const context = [
    `Template: ${template?.title ?? r.templateId}`,
    `Subsystem: ${r.subsystem}`,
    `Affected: ${r.affectedSystems.join(", ")}`,
    input.roadmapTarget ? `Roadmap target: ${input.roadmapTarget}` : null,
    input.ownerDirective ? `Owner directive: ${input.ownerDirective}` : null,
    r.roadmapItemId ? `Roadmap item: ${r.roadmapItemId}` : null,
    r.dependencyNodeIds?.length ? `Dependencies: ${r.dependencyNodeIds.join(", ")}` : null,
    r.blockerIds?.length ? `Blockers: ${r.blockerIds.join(", ")}` : null,
    r.technicalDebtRefs?.length ? `Tech debt: ${r.technicalDebtRefs.join(", ")}` : null,
    r.linkedCommitHashes?.length ? `Commits: ${r.linkedCommitHashes.join(", ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const concern = [
    `Architecture: ${r.architectureConcern}`,
    r.runtimeConcern ? `Runtime: ${r.runtimeConcern}` : null,
    r.scalingConcern ? `Scaling: ${r.scalingConcern}` : null,
    r.dependencyConcern ? `Dependency: ${r.dependencyConcern}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const constraints = [
    "MASTER: no fake metrics, heatmaps, or AI recommendations without real data.",
    "Autonomous execution must not fully freeze on review — parallel roadmap work allowed.",
    "Portal is SoT for ecosystem state; prefer persisted snapshots over live recompute.",
  ].join("\n");

  const markdown = `# AION Architecture Review Packet

## Meta
- **Title:** ${r.title}
- **Confidence:** ${r.confidence}
- **Status:** ${r.status}
- **Template:** ${r.templateId}

## Context
${context}

## Reasoning (Cursor)
${r.reasoning}

## Concerns
${concern}

## Proposed direction
${r.proposedDirection}

## Constraints
${constraints}

## Questions for reviewer (ChatGPT)
${questions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

---
*Generated by AION orchestration bridge — paste into ChatGPT architecture review.*
`;

  return {
    generatedAt: new Date().toISOString(),
    markdown,
    sections: {
      context,
      concern,
      constraints,
      proposedDirection: r.proposedDirection,
      questionsForReviewer: questions,
    },
  };
}
